os: Visual Studio 2017

build:
  verbosity: detailed

environment:
  matrix:
  - Build: rtc
    Configuration: Debug

platform:
- x64

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule init
  - git submodule update

build_script:
  - mkdir build
  - cd build
  - cmake .. -G"Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%Configuration% -DBOOST_ROOT=C:\Libraries\boost_1_67_0 
  - cmake --build .

test_script:
  - ps: |
      & ctest -V -j nproc
